// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package models

import (
	"errors"
	"fmt"
)

const (
	// OptionTypeSingleChoice is a OptionType of type single_choice.
	OptionTypeSingleChoice OptionType = "single_choice"
	// OptionTypeMultipleChoice is a OptionType of type multiple_choice.
	OptionTypeMultipleChoice OptionType = "multiple_choice"
)

var ErrInvalidOptionType = errors.New("not a valid OptionType")

// String implements the Stringer interface.
func (x OptionType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x OptionType) IsValid() bool {
	_, err := ParseOptionType(string(x))
	return err == nil
}

var _OptionTypeValue = map[string]OptionType{
	"single_choice":   OptionTypeSingleChoice,
	"multiple_choice": OptionTypeMultipleChoice,
}

// ParseOptionType attempts to convert a string to a OptionType.
func ParseOptionType(name string) (OptionType, error) {
	if x, ok := _OptionTypeValue[name]; ok {
		return x, nil
	}
	return OptionType(""), fmt.Errorf("%s is %w", name, ErrInvalidOptionType)
}

const (
	// QuestionTypeStatusActive is a QuestionTypeStatus of type active.
	QuestionTypeStatusActive QuestionTypeStatus = "active"
	// QuestionTypeStatusInactive is a QuestionTypeStatus of type inactive.
	QuestionTypeStatusInactive QuestionTypeStatus = "inactive"
)

var ErrInvalidQuestionTypeStatus = errors.New("not a valid QuestionTypeStatus")

// String implements the Stringer interface.
func (x QuestionTypeStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x QuestionTypeStatus) IsValid() bool {
	_, err := ParseQuestionTypeStatus(string(x))
	return err == nil
}

var _QuestionTypeStatusValue = map[string]QuestionTypeStatus{
	"active":   QuestionTypeStatusActive,
	"inactive": QuestionTypeStatusInactive,
}

// ParseQuestionTypeStatus attempts to convert a string to a QuestionTypeStatus.
func ParseQuestionTypeStatus(name string) (QuestionTypeStatus, error) {
	if x, ok := _QuestionTypeStatusValue[name]; ok {
		return x, nil
	}
	return QuestionTypeStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidQuestionTypeStatus)
}
