// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package models

import (
	"errors"
	"fmt"
)

const (
	// QuizVisibilityPublic is a QuizVisibility of type public.
	QuizVisibilityPublic QuizVisibility = "public"
	// QuizVisibilityPrivate is a QuizVisibility of type private.
	QuizVisibilityPrivate QuizVisibility = "private"
)

var ErrInvalidQuizVisibility = errors.New("not a valid QuizVisibility")

// String implements the Stringer interface.
func (x QuizVisibility) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x QuizVisibility) IsValid() bool {
	_, err := ParseQuizVisibility(string(x))
	return err == nil
}

var _QuizVisibilityValue = map[string]QuizVisibility{
	"public":  QuizVisibilityPublic,
	"private": QuizVisibilityPrivate,
}

// ParseQuizVisibility attempts to convert a string to a QuizVisibility.
func ParseQuizVisibility(name string) (QuizVisibility, error) {
	if x, ok := _QuizVisibilityValue[name]; ok {
		return x, nil
	}
	return QuizVisibility(""), fmt.Errorf("%s is %w", name, ErrInvalidQuizVisibility)
}
