// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package config

import (
	"errors"
	"fmt"
)

const (
	// EnvironmentProduction is a Environment of type production.
	EnvironmentProduction Environment = "production"
	// EnvironmentLocal is a Environment of type local.
	EnvironmentLocal Environment = "local"
)

var ErrInvalidEnvironment = errors.New("not a valid Environment")

// String implements the Stringer interface.
func (x Environment) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Environment) IsValid() bool {
	_, err := ParseEnvironment(string(x))
	return err == nil
}

var _EnvironmentValue = map[string]Environment{
	"production": EnvironmentProduction,
	"local":      EnvironmentLocal,
}

// ParseEnvironment attempts to convert a string to a Environment.
func ParseEnvironment(name string) (Environment, error) {
	if x, ok := _EnvironmentValue[name]; ok {
		return x, nil
	}
	return Environment(""), fmt.Errorf("%s is %w", name, ErrInvalidEnvironment)
}
